### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ggeidel** [Fuenfgeld/DMA2023TeamB#11]
Readme-File updaten.

**Comment by ggeidel** [comment]
Visuelle Zusammenfassung (Datenfluss) noch einfügen

**Comment by Aviebr** [comment]
Ich habe zum Read Me schon mal das Datenflussdiagramm hinzugefügt

**Comment by Aviebr** [comment]
Müssen wir eigentlich noch etwas im Read Me anpassen, außer die Darstellung mit veränderten Dokumenten und Prozessen?
