### ISSUE TITLE
System Umgebung klarmachen

### ISSUE THREAD

**Issue by ggeidel** [Fuenfgeld/DMA2023TeamB#12]
Information über Datenflussoptionen für Projekt.
(Beispiel: https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/System-Umgebung)

Danach in Meeting (19.2.):
Datenfluss festlegen und besprechen.

**Comment by Aviebr** [comment]
Was wollen wir in diesem Issue erreichen? Ist das Teil des Datenflussdiagramm Issues?

**Comment by ggeidel** [comment]
Nein, Datenflussdiagramm ist Issue #10 

Wir sollten besprechen, welche Pakete/Codes wir benutzen, dazu habe ich als Referenz ATeam verlinkt

**Comment by Aviebr** [comment]
ok

**Comment by Aviebr** [comment]
https://github.com/Fuenfgeld/DMA2023TeamB/wiki/System-Umgebung. Passt das so für euch?
