### ISSUE TITLE
Star-Schema des DW draften

### ISSUE THREAD

**Issue by Aviebr** [Fuenfgeld/DMA2023TeamB#13]
Erstellung eines Star-Schemas basierend auf den Daten, die wir in unserem Datawarehouse verwenden werden

**Comment by Aviebr** [comment]
https://github.com/Fuenfgeld/DMA2023TeamB/blob/ddcc7aa2827f9f114124c25b3ff4cc952b171915/DW%20Star%20Schema.png

Schaut euch das bitte mal an, ob es so ok ist

**Comment by ggeidel** [comment]
siehe #30
