### ISSUE TITLE
Vervollständigung Quelldaten 

### ISSUE THREAD

**Issue by Aviebr** [Fuenfgeld/DMA2023TeamB#15]
- Technische Felder um ein Beschreibungsfeld ergänzen. 
- Es genügt, sich auf Daten fokussieren, die wir im DW analysieren werden

**Comment by Aviebr** [comment]
Ich habe noch die Quelldaten für die externen Tabellen hinzugefügt. https://github.com/Fuenfgeld/DMA2023TeamB/wiki/Externe-Tabellen.

**Comment by ggeidel** [comment]
Schlüssel 🔑  siehe Tabelle careplans noch für alle anderen ergänzen? Oder überflüssig für euch?
@Aviebr @JPTakoh

**Comment by ggeidel** [comment]
#15 Datentabellen nun komplett.
