### ISSUE TITLE
Datenqualitätsprozess beschreiben

### ISSUE THREAD

**Issue by Aviebr** [Fuenfgeld/DMA2023TeamB#17]
- Verwendete Daten sind bereits aufgeführt
- Prozess muss beschrieben werden, wie Datenbereinigung und ETL vorgenommen wird 
-

**Comment by Aviebr** [comment]
Müssen wir für dieses Issue noch etwas machen?

**Comment by ggeidel** [comment]
Ja, ist noch offen, kann ich mich drum kümmern

**Comment by Aviebr** [comment]
@ggeidel : haben wir es schon geupdatet oder ist das Issue noch offen?
