### ISSUE TITLE
Adaptation ETL Prozess auf zu extrahierende Daten

### ISSUE THREAD

**Issue by ggeidel** [Fuenfgeld/DMA2023TeamB#19]
ETL Vorlage auf spätere Fragen für Warehouse zuschneiden

**Comment by Aviebr** [comment]
Ich habe einen Syntax Fehler bei create_tables gefunden. Hier wäre der angepasste Code:  create_tables = [create_patients_info, # patient data
                     create_conditions_info, create_procedures_info, create_devices_info,  # symptoms and procedure data
                     create_medications_info, # medication data
                     create_immunizations_info # immunization info
                     ]

**Comment by ggeidel** [comment]
Top! Ist ja schon jetzt über Pull request gemerged!

**Comment by Aviebr** [comment]
Skript funktioniert, Issue überflüssig
