### ISSUE TITLE
ETL-Prozess File

### ISSUE THREAD

**Issue by ggeidel** [Fuenfgeld/DMA2023TeamB#29]
Können wir das ETL-Prozess File löschen, da wir jetzt ein ETL-Prozess rev File haben?

**Comment by Aviebr** [comment]
Wie besprochen: Anastasia erstellt Star-Schema, Glenn erstellt CSV Dateien und Übergabe an Jonathan zum Anpassen des Skripts.

**Comment by ggeidel** [comment]
Csv Dateien (grading, immunization und medication classification) erstellt, in Google drive Ordner hochgeladen für Implementation in Skript! #29

**Comment by ggeidel** [comment]
@Aviebr Star Schema sieht so sehr gut aus!

**Comment by ggeidel** [comment]
#29 bei Zentralstelle muss noch encounter ID entfernt werden

**Comment by Aviebr** [comment]
Nach unserer gesterigen Diskussion, haben wir jetzt das finale ETL-Skript?

**Comment by Aviebr** [comment]
@JPTakoh und @ggeidel : könnnen wir dieses Issue nun schließen?

**Comment by ggeidel** [comment]
ETL-Prozess-File wie heute besprochen aktualisiert und committed. Funktioniert prima.
