### ISSUE TITLE
Star Schema vervollständigen

### ISSUE THREAD

**Issue by ggeidel** [Fuenfgeld/DMA2023TeamB#30]

**Comment by ggeidel** [comment]
@Aviebr Sieht schon sehr gut aus!

Encounters und Encounter_ID in Erkrankungsverlauf kann ex
Die Grading-Tabelle bezieht sich nur auf conditions, devices und procedures (weil medications und immunizations eine Klassifizierung erfahren, kein Grading).
- Wollen wir dann die Grading-Tabelle als Synopsis von conditions, devices und procedures machen? also deren jeweilige SNOMED-CT Codes und Description werden innerhalb der Grading Tabelle gegraded und dann der PK Grading referiert in der Tabelle Erkrankungsverlauf (hier fallen dann Conditions_, devices_ und procedures_code weg)
- Dann würde ich zusätzlich die Tabelle medication aufführen -> hier der Medications_code und einen medications_classificationID -> diese wird dann zum PK und in der zentralen Tabelle referiert
- Selbiges würde ich analog für Immunization Tabelle machen.

Damit hätten wir dann in der zentralen Tabelle Pat_ID, GradingCode, Medications_classificationID und immunizations_classificationID -> damit wäre dann alles Wichtige beisammen oder?

**Comment by Aviebr** [comment]
Passe ich wie besprochen bis morgen Abend an.

**Comment by Aviebr** [comment]
https://github.com/Fuenfgeld/DMA2023TeamB/blob/main/Darstellungen/Star%20Schema%20DWH.png Das neue Star Schema ist hier verlink. Daher schließe ich das Issue.

**Comment by Aviebr** [comment]
Ich hatte noch einen Primary Key falsch gesetzt. Den Fehler habe ich nun korrigiert: https://github.com/Fuenfgeld/DMA2023TeamB/blob/main/Darstellungen/DWH%20Star%20Schema.png
