### ISSUE TITLE
Datenanalyse 

### ISSUE THREAD

**Issue by Aviebr** [Fuenfgeld/DMA2023TeamB#32]
- Analyse der Demographie
- Analyse der Schweregrade der Erkrankungen 
- Testen unserer Hypothesen

**Comment by Aviebr** [comment]
https://github.com/Fuenfgeld/DMA2023TeamB/blob/main/Demographie_Analyse_ETL.ipynb Demographie Patienten habe ich hier abgelegt

**Comment by ggeidel** [comment]
@Aviebr Super Pitch! #32

**Comment by Aviebr** [comment]
https://github.com/Fuenfgeld/DMA2023TeamB/blob/main/Auswertung_DWH.ipynb. Ich schließe dieses Issue und verweise auf #45
