### ISSUE TITLE
Übersicht für Startseite erstellen

### ISSUE THREAD

**Issue by Aviebr** [Fuenfgeld/DMA2023TeamB#36]
Datenflussdiagramm ergänzen

**Comment by Aviebr** [comment]
Schau mal, wie du es findest: https://github.com/Fuenfgeld/DMA2023TeamB

**Comment by ggeidel** [comment]
Schon gut! Wir müssten im Verlauf nochmal Projektdesign und Doku anpassen. Hast du die Datei im Shared Drive abgelegt?

**Comment by ggeidel** [comment]
Wie sieht es mit dem Loop beim Datenfluss mit externen Quelldaten aus?

**Comment by Aviebr** [comment]
Den brauchen wir nun nicht mehr, oder? Ich werde die Darstellung entsprechend anpassen. Das PPT liegt bei uns im Drive ab.

**Comment by Aviebr** [comment]
Dieses Issue schließe ich
