### ISSUE TITLE
Externe Quelldaten nur Primary Key oder auch Foreign Key?

### ISSUE THREAD

**Issue by ggeidel** [Fuenfgeld/DMA2023TeamB#37]
https://github.com/Fuenfgeld/DMA2023TeamB/wiki/Externe-Tabellen

Snomed-Code ist doch auch foreign key?

**Comment by Aviebr** [comment]
Wohin sind denn die Externen Tabellen hingewandert? Die Seite scheint weg zu sein, bei dir auch?

**Comment by Aviebr** [comment]
Also so wie ich das verstanden habe, muss es in jeder Tabelle einen Primary Key geben, der kein Foreign Key ist. Deswegen würde ich für unsere Externen Tabellen sagen, es ist nur Primary Key. Korrigiere mich bitte, wenn ich falsch liege

**Comment by ggeidel** [comment]
Externe Tabellen sind unter ETL-Prozess aufgeführt, siehe neue Wiki-Liste

**Comment by ggeidel** [comment]
Wir könnten Grading als PK machen und FK SNOMED-CT Code?

**Comment by ggeidel** [comment]
wobei SNOMED-CT gleichzeitig PK ist?

**Comment by ggeidel** [comment]
Grading und Klassifikation nach Besprechung mit @Aviebr und @JPTakoh als PK
zusätzlich SNOMED-CT Codes als PK und FK
