### ISSUE TITLE
Cape Privacy Anonymisierung

### ISSUE THREAD

**Issue by ggeidel** [Fuenfgeld/DMA2023TeamB#38]
Implementierung in unser ETL-Skript möglich? https://docs.capeprivacy.com/getting-started/ Da sind auch Python-Codes für angeführt.
D.h. ich würde bei den Daten im ETL-Skript (wo wir sowieso keinen Vor- und Nachnamen mehr haben) die verbleibende ID nochmal anonymisieren mit dem Skript.

Frage -> ändert sich durch den Befehl auch die ID in den referierenden Tabellen oder entstehen dann Diskordanzen?

**Comment by ggeidel** [comment]
#Load encryption tools
!pip install cape_privacy

=> intitialize database ?

**Comment by Aviebr** [comment]
@JPTakoh : Nimmst du das mit auf als Coding Task?
