### ISSUE TITLE
Mapping Tabellen dokumentieren

### ISSUE THREAD

**Issue by ggeidel** [Fuenfgeld/DMA2023TeamB#39]

**Comment by Aviebr** [comment]
Ich kümmere mcih darum im Zuge der Aufräumarbeiten

**Comment by Aviebr** [comment]
@ggeidel  Arbeitest du grade an dem Issue? Die Tabellen, die ich anpasse und erstelle sind plötzlich alle weg

**Comment by Aviebr** [comment]
Haben wir diese Aktivität nun nach deinen Aktualisierungen abgeschlossen, Glenn?

**Comment by ggeidel** [comment]
Ist abgeschlossen
