### ISSUE TITLE
Draft des Datenmanagementplans

### ISSUE THREAD

**Issue by Aviebr** [Fuenfgeld/DMA2023TeamB#4]

**Comment by ggeidel** [comment]
@Fuenfgeld 
Im Rahmen der Anfertigung des Datenmanagementplans sind folgende Fragen aufgekommen:
Welche Lizenz gilt für die Daten? Synthea führt Apache License 2.0 auf.

Müssen trotz fiktiver Daten Urheberrechte beachtet werden (Angabe von Synthea vs. N/A)?

**Comment by ggeidel** [comment]
@Aviebr 
Bitte Kontaktdaten einfügen
@JPTakoh 
Bitte Kontaktdaten kontrollieren

**Comment by Fuenfgeld** [comment]
Die Daten sind frei verfügbar. In unserm Projekt behandeln wir die Daten aber wie Krankenhaus Quelldaten.

**Comment by Aviebr** [comment]
Kontaktdaten sind eingefügt
