### ISSUE TITLE
GitHub aufräumen

### ISSUE THREAD

**Issue by Aviebr** [Fuenfgeld/DMA2023TeamB#40]
- Alte Seiten löschen
- Inhalte anpassen und übertragen 
- Issues Meilensteine zuordnen und richtigen Status bei Projects assignen

**Comment by Aviebr** [comment]
https://github.com/Fuenfgeld/DMA2023TeamB/blob/main/Importierung%20Externer%20Tabellen%20in%20die%20SQL%20Quelldatenbank.ipynb - Da keine externen Tabellen mehr importiert werden, lösche ich dieses Skript

**Comment by Aviebr** [comment]
Initiales Inhaltsverzeichnis erstellt: https://github.com/Fuenfgeld/DMA2023TeamB/wiki/Inhaltsverzeichnis

**Comment by Aviebr** [comment]
Neues Star-Schema https://github.com/Fuenfgeld/DMA2023TeamB/blob/7e217e5d1f1325dac0af4fe8854047ffc3db312b/Darstellungen/Star%20Schema%20DWH%20Darstellung.png

**Comment by Aviebr** [comment]
https://github.com/Fuenfgeld/DMA2023TeamB/wiki/Datenflussdiagramm

**Comment by Aviebr** [comment]
https://github.com/Fuenfgeld/DMA2023TeamB/blob/main/README.md Projektübersichten final geupdated

**Comment by ggeidel** [comment]
SQL-Datenbank und DWH-Skript stark überarbeitet. Jetzt mit ausführlicheren Erklärungen.
Commit in dev-Branch führt leider zu Konflikt mit Main, sodass keine Übersicht im Pull-Request erzeugt wird.
Heute in Meeting Besprechen aufgefallener Punkte, die noch überarbeitet werden müssen.

**Comment by Aviebr** [comment]
Systemumgebung ist angepasst: https://github.com/Fuenfgeld/DMA2023TeamB/wiki/System-Umgebung

**Comment by ggeidel** [comment]
Aufräumen done
