### ISSUE TITLE
Datenanalyse Skript anpassen und Figures einfügen

### ISSUE THREAD

**Issue by Aviebr** [Fuenfgeld/DMA2023TeamB#45]

**Comment by Aviebr** [comment]
https://github.com/Fuenfgeld/DMA2023TeamB/blob/main/Auswertung_DWH.ipynb: Ich habe Figures und Beschreibungen eingefügt

**Comment by JPTakoh** [comment]
super Anastasia. Ich finde das sieht schon sehr gut aus

**Comment by Aviebr** [comment]
Nach einigen Anmerkungen von Glenn habe ich noch einiges eingefügt. https://github.com/Fuenfgeld/DMA2023TeamB/blob/main/Auswertung_DWH.ipynb @ggeidel : passt das so für dich?

**Comment by ggeidel** [comment]
@Aviebr 
o	Harmonisierung mit DWH
o	Beschreibung der einzelnen Schritte

**Comment by Aviebr** [comment]
#40 Habe es aus Versehen im falschen Issue submitted (40). Siehe hier: https://github.com/Fuenfgeld/DMA2023TeamB/blob/main/Codes/DWH_Analysis.ipynb

**Comment by ggeidel** [comment]
alles klar!
