### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/DMA2023TeamB#59]
- Bitte den Datenmanagement plan prominenter platzieren.
- 
![image](https://user-images.githubusercontent.com/32547123/222401153-32d09f73-ae92-4b60-8b9e-e912af4016e5.png)
Der Datenmanagement Plan ist der eingangspunkt eurere Doku das kommt nicht so raus.

- Gut geschriebene Auswertung verlinkt aber den colabbook code block in der Figure description.
- 
![image](https://user-images.githubusercontent.com/32547123/222401695-95183698-fe58-4f35-b769-c673aa99d953.png)
- DMP Ihr müsst bei den Lizenzen zwischen der Daten Lizenz und der code Lizenz unterscheiden

**Comment by Fuenfgeld** [comment]
Ich kann eure Colabbooks nicht ausführen wenn ich auf gdrive zugreifen muss. Habt ihrt die entsprechenden Rechte gegeben? Ansonsten schaut das die daten für die Analyse aus github bezogen werden.

**Comment by ggeidel** [comment]
> 

Zugriffsrechte wurden aktualisiert

**Comment by ggeidel** [comment]
Lizenzen aktualisiert

**Comment by ggeidel** [comment]
Datenmanagementplan prominenter dokumentiert.

**Comment by ggeidel** [comment]
Codeblocks aus Colabbook verlinkt zu Abbildungen.

**Comment by ggeidel** [comment]
@Fuenfgeld
Vielen Dank für das Feedback!
