### ISSUE TITLE
Datenmanagement-Plan vervollständigen

### ISSUE THREAD

**Issue by ggeidel** [Fuenfgeld/DMA2023TeamB#7]
Sobald Files angelegt und vervollständigt, damit Links gesetzt werden könnnen.
Zu vervollständigende Abschnitte sind bereits gekennzeichnet.

**Comment by Aviebr** [comment]
Ich habe die Details eingefügt

**Comment by Aviebr** [comment]
Was fehlt uns noch, um dieses Issue abzuschließen?

**Comment by ggeidel** [comment]
3.3. (datenanalysen und auswertung) -> sobald fertig ergänzen

3.4. Synopsis Datenfluss aktualisieren, sobald diese fertig (Issue #36

**Comment by Aviebr** [comment]
@ggeidel : Fehlt uns hier noch was?

**Comment by ggeidel** [comment]
Punkt 3.3 muss ergänzt werden
Datenflussdiagramm Abbildung/Link nicht intakt
Anonymisierung aktualisieren
